functionsDirectory = "/Users/devonmalloy/Desktop/claude/F1_Voice-Agent/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/devonmalloy/Desktop/claude/F1_Voice-Agent"
publishOrigin = "config"
functions = "/Users/devonmalloy/Desktop/claude/F1_Voice-Agent/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
included_files = ["knowledge-base.md"]

[[redirects]]
from = "/api/token"
to = "/.netlify/functions/token"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/search"
to = "/.netlify/functions/search"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]